### ISSUE TITLE
Intermittent kernel panic

### ISSUE THREAD

**Issue by sarsanaee** [sarsanaee/Chronometer#4]
This problem is still there! I have pulled the current commit in logfiles project, however, I got kernel panic in the first run!

**Comment by fshahinfar1** [comment]
I hope the commits with id `69dc53` to `7c1300` solves the issue.
Please checkout to the latest commit of `logfiles` branch.
I will not close the issue until it is ascertained that the bug is resolved.

**Comment by sarsanaee** [comment]
Panic! We need to investigate more!

**Comment by sarsanaee** [comment]
I checked with the new config and kernel 5.3.5. It seems to be functional.
