### ISSUE TITLE
Monitoring page table of a specific process

### ISSUE THREAD

**Issue by fshahinfar1** [sarsanaee/Chronometer#8]
we need to develop a better way to monitor a process.

1. How long should we sample the process page table?
2. What happens if the process has finished and we try to access its task_struct?
3. How should we demonstrate our stats?
- Aggregation of parameters
- Time series
4. Should we continue to write reaults in /dev/ptdump?
5. When should we call the kernel module?
6. Who calls the kernel module to begin the process?

**Comment by fshahinfar1** [comment]
Should the process being monitored be stopped before walking its page table? (signal SIGSTOP)

**Comment by sarsanaee** [comment]
Why being stopped?
